
###register

POST http://localhost:10000/promgt-api/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8

// {"username":"kinkim","password":"123456"}
{"username":"admin","password":"111111"}


###authenticate

POST http://localhost:10000/promgt-api/authenticate
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8

{"username":"kinkim","password":"123456"}
> {% client.global.set("auth_token", response.body.token); %}

###email
POST http://localhost:10000/promgt-api/email/login?email=im@kin.kim&eCode=123456
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Content-Encoding: utf-8

{"email":"im@kin.kim","eCode":"im@kin.kim"}
> {% client.global.set("auth_token", response.body.token); %}

###login
POST http://localhost:10000/promgt-api/login?username=kinkim&password=123456
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Content-Encoding: utf-8

> {% client.global.set("auth_token", response.body.token); %}


###hello

POST http://localhost:10000/promgt-api/hello
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8
Authorization:  {{auth_token}}

### currentUser

POST http://localhost:10000/promgt-api/currentUser
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8
Authorization:  {{auth_token}}








