spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://whoimi.com:3306/wiicom?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: mail@whoimi.com[pP/XcBb1plHO10KZoJ/+eKbhqWpUJd1up7q7pRppp7FAZ7Hhgze3Q38N4ODhXgqBSbtPB1XQNddYgGC+dqWiUV6MoH/Gdiwqbx3+Qu0qHX/vTpwSfxAMl0raPkErCQQuTd5P7gwZPH394MUeK87Y96HyFL0rYy7lIr3TaylyokxOqUHrNUS83NuhA6Eenv9H3TCYURFrSOoyLuTKgEW19SIM+dch5iciE/hHv4Yi2EGDmng9RX2ZnghUllKD3aSinYZ/Vhe3v38Rc9lGbfFI1XUE173REFnJfXj/hH05pDSgxK3vsRBhQYFs1xcVIwhjmXrOawB2CwwSLsViNXeUnA==]
      password: mail@whoimi.com[SD9Swa4+2rIH4Xzx470BaCx/YMD/EkQrtpdQ8JlwBiDjmj4jEUy50abypNvFgSc3DvPIzSSI0292hcBSujYZ3Wg1l2xfbs4zzkITSZTduAgYR7J7TcRLffCcUpn2bXUf5j8Fw6z7zfwF0ndJNrh2pSrtmtTUSKz2ntF7Ed8B4MBjcnp++xzikCzlPdas5crLF0MC4ic0mX/olHAyzTMIx4e+USzmjGBlyvH/iuZQyHw02NQhRDjXaYZWM/UTvC4k3os40XciWLn286veRU9uO6vDV60s2O9cCqxWU1UQl6HEeDhOc6FhG2XuzY+toVKZD+MfUziV1Taw+Jm8+RYGyg==]
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@172.16.2.19:1521/orcl
      username: mail@whoimi.com[hZtDyYocK1ybnBal82TYjerwcqhT2rzpZrEeMc2BO6L9kW3SiyHX2qppDCX98NDhMCUIHlm7sNnc+BxgPSyyJeFu1cHzXHXXG4xVAp4pJeByHK9654Vkk25neaHhYEDYPoqWmBvGeSwIX82E74Lm87tTgDlYnmTF9fHANS5D2kY+AZbxXTMqd/iopgyhyKPo3UGxTgRE7lgaNNdgaWh7E/ITohFkjgfD37Ucxq3KPDQkcRpoXc1h9772DGEzK8chuDdx4SGz8m80rwRezrDasObY7QamPJev5IcevaU1kSrR8Hefnyyf0XvdL+hq3SbEGyNrZFhp4/Wg+NN84+otOw==]
      password: mail@whoimi.com[sz3LTmIAFxM8OR21YfqCOFJkXrEvXAOzn+tooFM5mDZFSonDd4G+H5e+/Vd0Y9AwiIhhvol34pMMKazNKM5B9xp2cFsILA3sVeJ/zJK3ovEIkbTr28zwdbEffh7HvjVEiErfvaXMr6lNhCqmqL/1uICc2wVC4l4VBU7IPOucrx4nMtso/Hi/sfnwafCYe3s6Nb9nxKlny6t0CCHXFJZXL04rl6MAHJKeoSle7vM56wFfsVJLROcSVXQZAnnEsR2Cv6AJ+7YVHKeerD+tdbH/JdJUVpcxWmsysg9sw7jOhxKgjQ7KPadjSRe0rb8eIWv8RDl0XNQRCA2Drl14mFV/rg==]
  data:
    redis:
      host: whoimi.com
      password: mail@whoimi.com[ofdVcHK+MRzXdlxj2GkZV48lSteJQ6TdqANjyLBxzrsC1NcgjPFSXcEhzBwxkZaCWzuVgUyrboHmOqw9Cjmr/2YqvXS3omKJokfwpNgtd0FXKcA2TpUn1dFcF+iXf47bfsaxrWx4Sizk0dqCe6iOkkAxhV5XsDHy2YWPxdWXlFIR0p5qGvrgR6AHUx+fxVfw7YptfI7Hk8g9dbTDLpQva0GAcWe5HizCnx88VXoiC+cBa1lVcX+77Qj7i33oaZczvkDh06ehmsm3pQAZjtIbQeV+6m1YVIMqrHyR4NgkZb6cMicUSxYmVvxs/NEvDgOPlG3kz99xKAChx29n8ys3Jw==]
      port: 6379
      database: 0
jasypt:
  encryptor:
    #    algorithm: PBEWITHHMACSHA512ANDAES_256
    #    password: a2lua2lt
    property:
      prefix: "mail@whoimi.com["
      suffix: "]"
    private-key-format: pem
    public-key-format: pem
    #    private-key-location: classpath:id_rsa_pkcs8
    #    public-key-location: classpath:id_rsa_pkcs8.pem
    private-key-location: file:C:\\Users\\whoimi\\.ssh\\id_rsa_pkcs8
    public-key-location: file:C:\\Users\\whoimi\\.ssh\\id_rsa_pkcs8.pem
